### ISSUE TITLE
make NKRO default when NKRO_ENABLE

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#100]
ATM NKRO is not used by default even on fimrware built with `NKRO_ENABLE`. This is a bit confusing and not clear to users due to not documented well.
https://github.com/tmk/tmk_keyboard/wiki/FAQ#wiki-nkro-doesnt-work

Expected compatibity issue with BIOS is reason why NKRO is not default. But I didn't look into what happens in fact.

TODO:
- document well, or
- make NKRO default when built with NKRO_ENABLE(this will be natural for users)
- research on issues NKRO causes on BIOS or other devices

**Comment by agodinhost** [comment]
I added some code to write the keyconf byte according to the Makefile.lufa settings.
https://geekhack.org/index.php?topic=41989.msg1580329#msg1580329

**Comment by tmk** [comment]
Though again. I'm chaging my mind again.

Some projects are built with enabling NKRO by default and NKRO can be problematic on BIOS or other specific platform for most of users.

It is safe that NKRO is deactivated by default even if firmware is built with NKRO feature and users have to press Magic or BootMagic keys to activate NKRO. Most of users don't have to care about NKRO and only some who want NKRO should know about those Magic keys.


Probably I'll revert this change later.
common/host.c
```
 #ifdef NKRO_ENABLE
-bool keyboard_nkro = false;
+bool keyboard_nkro = true;
 #endif
````
