### ISSUE TITLE
Modifiers that are only on the base layer can get stuck

### ISSUE THREAD

**Issue by pianohacker** [tmk/tmk_keyboard#105]
(This is on the ErgoDox, but I believe this is a tmk issue.)

So, I have a key which is LCTRL on layer 0 and BACKSPACE on layer 1, and another that is bound to ACTION_LAYER_MOMENTARY(1). If I hit the layer 1 key, then backspace, everything is kosher. However, if I press LCTRL, then layer 1, then release then release LCTRL, then layer 1, the LCTRL modifier bit stays stuck in the keyboard report. This makes sense, as del_mod_bit never gets called, as that keycode doesn't exist in that layer.

Is there some way to work around this? I'd rather not use tap modifiers unless I have to.

**Comment by DreymaR** [comment]
My thought on this topic is: When do we need modifier states preserved upon a layer change?

I would think that we don't! When I change layers, at least temporarily, I could live with a clean modifier slate.

Therefore, making an ACTION_LAYER_MOMENTARY_CLEARMODS() action that activates a layer upon press and upon release not only deactivates the layer but also all mod states seems like a good solution to me. No more stuck modifiers, at a low cost.

**Comment by DreymaR** [comment]
A more fancy and robust way:

Add ACTION_LAYER_MOMENTARY_SM() which is like the non-SM version except it performs MOD_STORE on key down and MOD_RESTORE on key up (like the macro actions).

This way, we're guaranteed the same mod state when we leave our temp layer as we had before. This solution would be fully backwards compatible.

Alternatively, unless anyone can think of a counter-example to this being useful behavior, you might just add the SM/RM functionality to the old ACTION_LAYER_MOMENTARY(). More dramatic but simpler.

**Comment by tmk** [comment]
Fixed at 	ba2883f
