### ISSUE TITLE
Shift weirdness with pipe |

### ISSUE THREAD

**Issue by mattharrison** [tmk/tmk_keyboard#117]
I've been running the tmk fw on my ergodox for a bit now. Am running into an issue where when I hit pipe (|), a backslash is usually entered as well (ie |\). (I had to delete the backslash from the pipe back there :)).

This does not appear to happen with other shifted keys, nor did it happen with Ben's fw.

Any ideas?

**Comment by tmk** [comment]
It seems like Linux no longer have this problem now, on 4.4.0-36(Ubuntu 16.04 LTS) at least.

**Comment by tmk** [comment]
Seems that this commit of Linux kernel fixed this issue. Its comment is really worth reading.
https://github.com/torvalds/linux/commit/6ce901eb61aa30ba8565c62049ee80c90728ef14

and this supplied proper conditional clause.
https://github.com/torvalds/linux/commit/8e7b341037db1835ee6eea64663013cbfcf33575#diff-f35f6b78ead6796aeaf38a7414178d43
