### ISSUE TITLE
PS/2 refactoring

### ISSUE THREAD

**Issue by bgould** [tmk/tmk_keyboard#129]
Refactoring of PS/2 Interfaces
------------------

There are a number of open issues related to PS/2:

 #76 PS/2 mouse support doesn't work 
 #82 PS/2 converter: hot plug
 #83 PS/2 protocol: WAIT() wait_[clock|data]_[hi|lo] doesn't work as expected
#101 PS/2 Mouse and MouseKey integration

Seems like a lot of these mention refactoring the PS/2 code.

In addition I would like to add the following functionality for my project:

1. Create a TMK Keyboard "host" implementation that causes the firmware to act as PS/2 device(s), both mouse and keyboard.  Consumer keys for a PS/2 device are sent on the keyboard data lines, so most functionality of TMK keyboard could be implemented over PS/2.  If the host device's PS/2 supports it, it should be possible to implement both of these devices on a single mini-DIN 6 connector.

2. At least some USB AVRs allow for direct drive of the D+ and D- so it should be possible to automatically detect if the remote host is a USB host or a PS/2 host, and then choose an appropriate TMK host implementation.  Resources:
  * [UPOE - USB Software Output Enable register (Section 20.10.2, pg. 195)][2]
  * [USB and PS/2 Detection (Section 1.5.1, pg. 12)][3]
  
In order to get these things done, it would at the very least be necessary to refactor the PS/2 code to support functions for device mode, as well as the ability to support multiple PS/2 interfaces.  At the present time, only one PS/2 interface can be configured, and it must be implemented as a host.  In addition, to maintain proper timings it most likely will be necessary for the hosts and devices to coordinate sending and receiving data, and inhibit communicating when necessary.

In order to maintain backward compatibility, it probably would be a good idea to leave the existing PS/2 functions in place and create all new functions for the enhancements, similar in the way that legacy keymaps are handled.

My thought is generally that a central PS/2 "subsystem" could be created that have host and device interfaces enabled/disabled on it, and that subsystem could provide the low level transport functions and coordinate the timing of everything.  The subsystem could also keep track of what is and is not connected and be queried by other components of the firmware for those facts.

Once that is complete, higher level functions can be built on top of the "subsystem" to implement common functionality, such as the host implementation acting as PS/2 devices described above.

I don't want to step on work that you're already doing, but since I'm going to need this for my project anyhow I thought that I could offer to take a stab at it if its not already being worked on.  Any suggestions or comments that you have would of course be welcomed.
  
[1]: http://pinouts.ru/InputCables/Ps2KeyboardYThinkpad.shtml "pinouts.ru: PS/2 Keyboard (IBM Thinkpad) Y adapter"
[2]: http://www.atmel.com/Images/doc7799.pdf "(20.10.2, ATmega16u2 datasheet, pg. 195)"
[3]: http://www.freescale.com/files/microcontrollers/doc/ref_manual/DRM014.pdf "(Section 1.5.1, USB and PS/2 Multimedia Keyboard Interface, Rev. 1 12 Freescale Semiconductor, pg. 12)"

**Comment by ndhemingway** [comment]
I noticed this got closed not too long ago.  I've just started work on a Bluefruit + Arduino + TMK conversion for an IBM M13 (black with trackpoint) so would like to implement.  However I'm following this guide - https://learn.adafruit.com/convert-your-model-m-keyboard-to-bluetooth-with-bluefruit-ez-key-hid/ so will be wrapping the AVR code back out to Arduino-land.
