### ISSUE TITLE
ADB-USB: Adjustable keyboard media buttons doesn't  work

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#130]
http://geekhack.org/index.php?topic=14290.msg1408316#msg1408316
"
I confirmed the issue you mentioned on Adjustable Keyboard, the keyboard stops working and only replys with error code 'FFEF' instead of keycode after those media keys are pressed.

Hmm, those media keys  don't yield a keycode unlike other keys, it may need some special initialization or procedure to get keycode of the keys. we'll need to look for the information among old apple documentations.
"

**Comment by tmk** [comment]
Adjustable keyboard's media keys are supported now.
https://github.com/tmk/tmk_keyboard/commit/1bce71fbf7874cc0169860cd0b6f1a59fdec9993

The keyboard has two address; 0x02 for main keyboard part and 0x07 for media keys. So converter has to poll the two address.

'Service Request'(Srq) will contribute to polling efficiency when you have to poll multiple addresses but it is not supported now.

**Comment by tjweir** [comment]
This is awesome!
