### ISSUE TITLE
tapping CTRL not working in macros (Ergodox)

### ISSUE THREAD

**Issue by kaimi** [tmk/tmk_keyboard#136]
I’m using @cub-uanic’s Ergodox code, but apparently it’s most likely a general issue: cub-uanic#6.

In this macro 

```
MACRO( I(50), T(LCTRL), T(LCTRL), W(255), W(255), T(ENTER), END)
```
https://github.com/kaimi/tmk_keyboard/blob/1.0.1/keyboard/ergodox/keymap_neo.h#L402

only the ENTER is registered, both LTCTRL are silently omitted. XEV output:

```
KeyPress event, serial 32, synthetic NO, window 0x3a00001,
    root 0xa2, subw 0x0, time 27317479, (-128,418), root:(559,457),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
"   XmbLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x3a00001,
    root 0xa2, subw 0x0, time 27317535, (-128,418), root:(559,457),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False
```

I tried seperate D(LCTRL), U(LCTRL) and even reducing the macro to just T(LTCRL), T(ENTER). Don’t work either.

**Comment by tmk** [comment]
This commit e852582d8b probably fixed this problem.
