### ISSUE TITLE
Teensy 3 Support

### ISSUE THREAD

**Issue by bgould** [tmk/tmk_keyboard#140]
I've got preliminary support for Teensy 3.0/3.1 working... I based my work on the mbed stuff from the dev branch and was able to get ps2_usb working

I merged the dev branch into the master branch, and then added Teensy 3 support on top of that, so it should merge pretty cleanly with your master branch if/when you choose to do so

My implementation probably needs a little bit of cleaning up, especially since I'm fairly certain I broke the other builds :)

Nevertheless, here the branch with my changes if you'd like to take a look:

https://github.com/bgould/tmk_keyboard/compare/tmk:master...2219257d3a7bc50832948a93abdabdacf5f4ac8d

Also, the following things aren't working yet:
 * no NKRO yet
 * scroll wheel left and right don't appear to be available in the Teensy 3 libraries
 * only 8 media keys for consumer keys
 * no system keys
 * need to use `teensy_gateway` program instead of `hid_listen` for debug console
 * EEPROM not implemented, thus BOOTMAGIC does not work
 * command.c does not compile yet; thus COMMAND_ENABLE does not work

If you're interested in merging in any of these changes I can do whatever cleanup is necessary first and do a pull request

Thanks

**Comment by tmk** [comment]
Cortex-M(mbed) support was integrated now.
