### ISSUE TITLE
Send accentuated characters 

### ISSUE THREAD

**Issue by numjcp** [tmk/tmk_keyboard#145]
Dears,

I use tmk with a teensy in an atreus keyboard variant.

I can't figure out how to map a key directly (i.e. without using any mod key) to an accentuated character  for instance the é character
(I m french I use a lot of é) is it possible ?

How can i do it with TMK ?

Same question for the ^ character ? how to get it on a direct key ?

best regards.

**Comment by tmk** [comment]
See this FAQ too.

https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#input-special-charactors-other-than-ascii-like-c%C3%A9dille-%C3%87
