### ISSUE TITLE
Keyboard prevents standby

### ISSUE THREAD

**Issue by quantentunnels** [tmk/tmk_keyboard#149]
I'm using Ubuntu 14.04. and whenever I want to go to standby, the machine powers down and then right back up again. When I unplug the keyboard the machine stays in standby mode.

I'm using cubuanics fork on my ergodox (cub-uanic/tmk_keyboard@7c1ed424f1011aa214b9539a083da318050e21b7).

**Comment by cub-uanic** [comment]
Should be fixed now in Ergodox port ([cub-uanic/tmk_keyboard](https://github.com/cub-uanic/tmk_keyboard)).
