### ISSUE TITLE
About USB Vendor ID (VID) and Product ID

### ISSUE THREAD

**Issue by cj1324** [tmk/tmk_keyboard#150]
GH60 use VENDOR_ID 0xFEED  PRODUCT_ID 0x6060 ? why ?

http://www.arachnidlabs.com/blog/2013/10/18/usb-if-no-vid-for-open-source/

**Comment by Nephiel** [comment]
There is a way to get free unique USB IDs assigned to your Open Source projects; see http://pid.codes/

**Comment by KulaGGin** [comment]
What if someone uses VID and PID they want in their project without buying it for $5000 from USB-IF? And then this someone sells their product to people. Can USB-IF sue them? Will they win? How does it work?
