### ISSUE TITLE
USE_LEGACY_KEYMAP breaks build

### ISSUE THREAD

**Issue by bjd-pfq** [tmk/tmk_keyboard#181]
When commenting out USE_LEGACY_KEYMAP in config.h, the build breaks:

obj_sun_usb/common/keymap.o: In function `action_for_key':
tmk_keyboard-20150130/converter/sun_usb/../../common/keymap.c:32: undefined reference to `keymap_key_to_keycode'
tmk_keyboard-20150130/converter/sun_usb/../../common/keymap.c:35: undefined reference to `keymap_fn_to_action'
collect2: error: ld returned 1 exit status
make: *** [sun_usb.elf] Error 1

**Comment by tmk** [comment]
Don't comment out that macro. Sun converter still uses legacy keymap.
