### ISSUE TITLE
Feature Request: Reset Teensy Button!

### ISSUE THREAD

**Issue by joshfrese** [tmk/tmk_keyboard#187]
First off, thanks for the firmware. It would be nice to have a way to map a keyboard press to reboot the teensy or put it into the mode that accepts new software.

**Comment by p3lim** [comment]
<kbd>LShift</kbd>+<kbd>RShift</kbd>+<kbd>Pause</kbd> will jump to the bootloader.
It's part of the magic commands.

**Comment by kejadlen** [comment]
See https://github.com/cub-uanic/tmk_keyboard/blob/master/keyboard/ergodox/keymap_cub.h#L468-L474 for an example of how to use it in a keymap.

**Comment by p3lim** [comment]
You can also override magic commands, like so:
```C
bool command_extra(uint8_t code)
{             
    switch (code) {
        case KC_B:
            clear_keyboard();
            print("\n\nJump to bootloader... ");
            _delay_ms(1000);
            bootloader_jump(); // not return
            print("not supported.\n");
            break;
    }
    return false;
}
```

**Comment by joshfrese** [comment]
Ah, very nice thanks.
