### ISSUE TITLE
Auto-detect USB device path for non-teensy?

### ISSUE THREAD

**Issue by technomancy** [tmk/tmk_keyboard#188]
When using `make teensy` you don't have to specify the path to the USB device since `teensy_loader_cli` does this for you. But when using `avrdude` you need to write out your own `PROGRAM_CMD` option that includes the path to the appropriate USB device, which can be confusing since there's no one cross-platform setting you can use for this.

What if we added a `make avrdude` target that could invoke `avrdude` with a guess the correct auto-detected arguments based on the current OS?

**Comment by tmk** [comment]
If it can be implemented easily  avrdude should have that option already. Lastime I skimmed the manual I didn't find it.

**Comment by technomancy** [comment]
I figured it couldn't be that hard since the teensy loader does this, but it loops through all USB devices using syscalls and looks for a specific Vendor ID and Product ID match:

  https://github.com/PaulStoffregen/teensy_loader_cli/blob/master/teensy_loader_cli.c#L213

Probably wouldn't work here since the Vendor ID and Product ID can change. Too bad.
