### ISSUE TITLE
Don't firemware happy hacky keyboard

### ISSUE THREAD

**Issue by platinumthinker** [tmk/tmk_keyboard#209]
I have hhkb professional 2 rev a2. When i run
> make -f Makefile KEYMAP=hhkb dfu   
I see     
>>dfu-programmer atmega32u4 erase --force
>>dfu-programmer: no device present.

lsusb 
Bus 005 Device 004: ID 0853:0100 Topre Corporation HHKB Professional

dfu-programmer --version
dfu-programmer 0.7.2

**Comment by tmk** [comment]
Original controller of HHKB is not programmable. That firmware is for 'Alt contoller', not original one.

Read README.
```
I wanted to add some features like vi cursor and mouse keys to my HHKB but its controller is not programmable and firmware source code is not open, of course. This means customizing this keyboard needs to replace original controller with programmable one.
```

You can make your own DIY controller or buy TMK made one from me.
https://geekhack.org/index.php?topic=12047.0
