### ISSUE TITLE
Nice work.... Could this be done for an ADB Mouse?

### ISSUE THREAD

**Issue by gweep** [tmk/tmk_keyboard#220]
I have a nice three button optical ADB mouse and a joy stick that I'd like to put back in service.    With all the work you've done with the keyboard; how far away is a ADB mouse to usb conversion?
Thanks

**Comment by tmk** [comment]
First, connect them and report back.
If they don't work let us know detailed of your problem.

**Comment by tmk** [comment]
Oops, I didn't update README but ADB converter got support for mouse recently. So you can use mouse now.

I'll update README later.

**Comment by gweep** [comment]
Thanks very much,   I’ll try it soon.
