### ISSUE TITLE
compatible usb boards

### ISSUE THREAD

**Issue by LimitlessPotential** [tmk/tmk_keyboard#227]
not so much an issue but a question. whats the most suitable adaptor board for this? I've seen projects blogged online using teensy 2.0, would the LC be suitable for this?

I'm not that highly familiar with all this so any help would be great

Thanks

**Comment by tmk** [comment]
TMK boards, Of course!
https://geekhack.org/index.php?topic=72052.0

**Comment by kaansoral** [comment]
a TMK 60% universal PCB would've been nice :)
