### ISSUE TITLE
ACTION_LAYER_TAP_KEY does not pop mode when released

### ISSUE THREAD

**Issue by Miko4** [tmk/tmk_keyboard#243]
I have my spacebar as a FN-Key, that is mapped to ACTION_LAYER_TAP_KEY(1,KC_SPACE). That works both for wrinting space and for entering layer 1 as expected. I however expect it do return to the previous layer (or just 0) when i release the key, just like for TAP_MOD the modifier key is not pressed anymore when the key is released. I'm not sure If this is a bug or intended. I'd like to make releasing the space key in layer 1 to enter layer 0, but as i understood i only can react to key presses.

As explanation: As long as I press space I want JKLI to be my courser keys. 

I do use the ergodox-fork from https://github.com/cub-uanic/tmk_keyboard.git so maybe I'm not up-to date.

Probably unrelated to #241

**Comment by tmk** [comment]
Not sure what your problem is. Post your keymap.

**Comment by Miko4** [comment]
Here is my keymap.c : https://gist.github.com/Miko4/602f9cec6017d690c2b3

My problem is that once I entered Layer 1 by pressing space I do not leave it by releasing space.

**Comment by tmk** [comment]
You have to place TRNS on the place instead of FN4. And you also should place TRNS instead of ENT on layer 1.
Basically you should TRNS on destination layer for layer switch keys and modifier keys.

**Comment by Miko4** [comment]
Do I understand it correctly that every layer change key has to stay the same for all higher layers?

**Comment by tmk** [comment]
Basically yes.
