### ISSUE TITLE
adb_usb firmware causes phantom mouse Yosemite 10.10.5

### ISSUE THREAD

**Issue by MaxSchultz** [tmk/tmk_keyboard#249]
I flashed the latest adb_usb firmware and upon reboot of the Teensy: the mouse comes to life and scrolls to the top left corner of the screen continuously.

I rolled back to https://github.com/tmk/tmk_keyboard/commit/7860d09914dba5e7d2d6c1c25b62b49d1bbd2591#diff-e0164cbe418fba1d5d5f6c0eaf6f75cc version of the Makefile and the issue stopped.

Thank you to the TMK team for all your excellent work!

**Comment by tmk** [comment]
Do you have pull-up resistor?

I'd seen poeple suffered from same problem in a forum but I didn't know why. Some of them had clearly hardware problems like bad connection and wiring.
https://geekhack.org/index.php?topic=14290.msg1754134#msg1754134

But now I finaly got it.  You must have a pull-up resistor, mouse function doesn't work without it. If you configure without mouse it may work withoug pull-up resistor.

***Anyway pull-up resistor is a must-have.***
