### ISSUE TITLE
Infinity keyboard: blinking LED

### ISSUE THREAD

**Issue by priyadi** [tmk/tmk_keyboard#260]
With Infinity keyboard, the LED is always blinking. This gets very annoying with a translucent case.

It doesn't happen with the stock firmware: LED is off unless when DFU mode is active.

**Comment by tmk** [comment]
See main.cpp, you will see code to be changed there.
Another workaround is desoldering the LED :D

**Comment by tmk** [comment]
BTW, you may want to try flabbergast's ChibisOS version instead of mbed.org. This supports mouse key and media keys unlike mbed. And with this version probably LED won't bother you.

See this.
https://github.com/tmk/tmk_keyboard/tree/flabbergast-tmk_chibios/keyboard/infinity_chibios
