### ISSUE TITLE
Media keys on Infinity not recognized in Linux, Windows

### ISSUE THREAD

**Issue by nbravo** [tmk/tmk_keyboard#261]
I'm using an Infinity from the latest Massdrop batch and the volume down, volume up, and mute keys don't work. I've tried both Windows 8 and Ubuntu 14.04. When I use a keycode tester like http://www.asquare.net/javascript/tests/KeyCode.html it does not even detect that a keycode is being sent for those keys.

**Comment by tmk** [comment]
tmk/mbed protocol doesn't support those media keys, mouse key and NKRO at this time.
https://github.com/tmk/tmk_keyboard/tree/master/tmk_core/protocol/mbed
https://github.com/tmk/tmk_keyboard/tree/master/keyboard/infinity

While flabbergast's tmk/chibios supports those functions and you can use them on Infinity now.
https://github.com/tmk/tmk_keyboard/tree/flabbergast-tmk_chibios/tmk_core/protocol/chibios
https://github.com/tmk/tmk_keyboard/tree/flabbergast-tmk_chibios/keyboard/infinity_chibios
