### ISSUE TITLE
Infinity60/chibios drop keys

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#268]
It fails to register keys when fast typing or rubing keys test.

Rubing keys test:
WIth one finger tip rub keys in a row as fast as possible, like 1234567890-=\` or qwertyuiop[].

SOLUTION:
Chibios protocol has 5ms delay in main loop, it causes this. Probably it can be removed safely.
```
diff --git a/tmk_core/protocol/chibios/main.c b/tmk_core/protocol/chibios/main.c
index 9607f1a..b62cfa9 100644
--- a/tmk_core/protocol/chibios/main.c
+++ b/tmk_core/protocol/chibios/main.c
@@ -135,6 +135,5 @@ int main(void) {
     }
 
     keyboard_task();
-    chThdSleepMilliseconds(5);
   }
 }
```

**Comment by flabbergast** [comment]
Yep, this is a problem. I originally put it there sort-of at random. It may be useful to put some delay here, just because the ARM hardware generally runs at least 3 times faster than AVR, so the debouncing numbers won't "match".
