### ISSUE TITLE
Add ability to use strings

### ISSUE THREAD

**Issue by JuanPotato** [tmk/tmk_keyboard#290]
I want to easily be able to send strings like "( ͡° ͜ʖ ͡°)" when I press a key, but it doesnt seem that this is possible without using macros to send the alt codes. Why not add a method to send strings.

**Comment by tmk** [comment]
Is that possible? Could you send pull request? I'll add it unless it changes tmk_core too much.

**Comment by bgould** [comment]
Seems like this might be difficult to achieve, and probably even more difficult to do it in a way that doesn't depend on the OS of the host computer.

**Comment by JuanPotato** [comment]
I know that it is possible as seen [here](http://randomnerdtutorials.com/teensy-username-and-password-auto-filler/), I would attempt to implement it if I had time to look through all the code. It seems simple enough, just send all the characters. Another option would be to add sending unicode characters in macros.

**Comment by JuanPotato** [comment]
@bgould Could you explain why?

**Comment by tmk** [comment]
It may be helpful to check this.

https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#user-content-input-special-charactors-other-than-ascii-like-cédille-Ç

**Comment by vovcacik** [comment]
Probably possible, but not practical at all.

You would need to create macro that sends unicode alt codes, which needs to be enabled on Windows in registry `EnableHexNumpad`. Who knows how this works on other OSes.

Seems like lot of pain with no good usecase.

**Comment by p3lim** [comment]
Use macros and a compose software on your OS, I do [this](https://github.com/p3lim/keyboard_firmware/blob/master/keymap.c#L78-L89) for norwegian letters (with a modified macro.c because of #116)

**Comment by bgould** [comment]
@JuanPotato The link @tmk posted is what I meant... there is no way to achieve this without making assumptions about the host operating system.

I use this macro to do special characters in X on GNU/Linux:

https://github.com/bgould/costar_tmk_keyboard/blob/master/keymap.c#L81-L106

But this certainly won't work on Windows, and there is no way for me to determine at runtime what OS my keyboard is hooked up to
