### ISSUE TITLE
Retrieving Modifier States

### ISSUE THREAD

**Issue by Eric-L-T** [tmk/tmk_keyboard#298]
I want to be able to change the function of a macro by holding down modifier keys. Is there something that I can put into the `if`statement to detect whether or not they are being pressed?

**Comment by tmk** [comment]
You can use this to know current keyboard report including modifiers.
https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/action_util.h#L27

**Comment by Eric-L-T** [comment]
Thank you. Sorry, I am a bit inexperienced in coding. What exactly should I be putting into my `if` statement?

**Comment by tmk** [comment]
Like this.
https://github.com/tmk/tmk_keyboard/blob/master/keyboard/hhkb/config.h#L40

**Comment by Eric-L-T** [comment]
That worked perfectly! Thanks again!

**Comment by Eric-L-T** [comment]
@tmk Hello? If this is impossible, please don't hesitate to tell me.

**Comment by tmk** [comment]
I think it is possible. Take time to traverse source codes under common directory, you will get idea.

**Comment by Eric-L-T** [comment]
.u,u,a.u,.ua 
> .u,.ua.ua.u
