### ISSUE TITLE
LT function does not switch back from higher layer after button release for certain keys

### ISSUE THREAD

**Issue by brokenalarms** [tmk/tmk_keyboard#308]
I'm not sure if this is already covered by #215, but it seems fairly fundamental and easy to reproduce.

For LT(FOO, BAR), it works as expected for BAR keys KC_ENT, KC_UP, even KC_Z (thus not just non-alphanumeric), but for certain keys (haven't isolated it exactly, but so far it appears to be the home row and KC_SPCE), holding the key just switches to layer FOO and gets stuck there. This means that unless you have a separate toggle switch for that particular layer, you're just stuck there forever....

Can try and fix myself too if you point me in the right direction (eg, where is the actual 'LT' function? I can't find it :P New to C, apologies!)

Thanks!

**Comment by tmk** [comment]
What's `LT()` ? I can't find it in my repo :(
Maybe you are reporting in wrong repo?

**Comment by brokenalarms** [comment]
I sure am. Meant for qmk (ergodox) then accidentally followed your post through from geekhack, they look similar. Sorry! >,
