### ISSUE TITLE
Additional Functionality Request: Mouse Jigglin'

### ISSUE THREAD

**Issue by redvers** [tmk/tmk_keyboard#319]
A basic request would be for a minute mouse-move every X minutes.  Purpose is to fool the HostOS into thinking someone is there.  My personal use-case is to work-around nested DPMS bugs which are killing me.

If it's something that's easy then awesome(!).  If it isn't I'll grab a stand-alone one and feel free to close this out.

Thanks for your consideration.

__red__

**Comment by Eric-L-T** [comment]
This is very easy to implement if you use [QMK](https://github.com/jackhumbert/qmk_firmware). If you want to stick with TMK, you will have to modify some files in `tmk_core`.

**Comment by eltang** [comment]
A quick update: if #323 is merged, you will not have to use QMK.
