### ISSUE TITLE
Source won't 'make'

### ISSUE THREAD

**Issue by theen** [tmk/tmk_keyboard#335]
I'm following the instructions but get the following:

`~/ergodox/tmk_keyboard/keyboard/teensy_lc_onekey $ make
../../tmk_core/tool/chibios/chibios.mk:88: ../../tmk_core/tool/chibios/chibios/os/common/ports/ARMCMx/compilers/GCC/mk/startup_kl2x.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:90: ../../tmk_core/tool/chibios/chibios/os/hal/hal.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:91: ../../tmk_core/tool/chibios/chibios/os/hal/ports/KINETIS/KL2x/platform.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:95: ../../tmk_core/tool/chibios/chibios/os/hal/boards/PJRC_TEENSY_LC/board.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:97: ../../tmk_core/tool/chibios/chibios/os/hal/osal/rt/osal.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:99: ../../tmk_core/tool/chibios/chibios/os/rt/rt.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:100: ../../tmk_core/tool/chibios/chibios/os/rt/ports/ARMCMx/compilers/GCC/mk/port_v6m.mk: No such file or directory

../../tmk_core/tool/chibios/chibios.mk:231: ../../tmk_core/tool/chibios/chibios/os/common/ports/ARMCMx/compilers/GCC/rules.mk: No such file or directory

make: *** No rule to make target ../../tmk_core/tool/chibios/chibios/os/common/ports/ARMCMx/compilers/GCC/rules.mk'. Stop.
`

I checked and the files mentioned actually don't exist.

**Comment by eltang** [comment]
You didn't get ChibiOS. See [these instructions](https://github.com/tmk/tmk_keyboard/tree/master/tmk_core/protocol/chibios).
