### ISSUE TITLE
Ergodox EZ layout?

### ISSUE THREAD

**Issue by anildigital** [tmk/tmk_keyboard#343]
Also will we get QWERTY and Norman layouts for it?

**Comment by eltang** [comment]
The official firmware for the ErgoDox EZ is [QMK](https://github.com/jackhumbert/qmk_firmware).

**Comment by fredizzimo** [comment]
For Ergodox EZ you will have to use the QMK fork of TMK. You can find it here https://github.com/jackhumbert/qmk_firmware.

And for Infinity Ergodox, you probably want to use my fork https://github.com/fredizzimo/infinity_ergodox.

**Comment by eltang** [comment]
I'm not sure what you're asking though. Although its default layout is QWERTY, the ErgoDox EZ is fully programmable.
