### ISSUE TITLE
I'm following the instructions but get the following:

### ISSUE THREAD

**Issue by sdh806** [tmk/tmk_keyboard#359]
I'm following the instructions but get the following:

/tmk_keyboard-master/keyboard/stm32_f103_onekey

$ make -f Makefile
Compiling crt0_v7m.S
process_begin: CreateProcess(NULL, arm-none-eabi-gcc -c -mcpu=cortex-m3 -Wa,-amhls=build/lst/crt0_v7m.lst -DCORTEX_USE_FPU=FALSE -DCORTEX_VTOR_INIT=0x2000 -DMOUSEKEY_ENABLE -DMOUSE_ENABLE -DEXTRAKEY_ENABLE -DNO_PRINT -DNO_DEBUG -DCOMMAND_ENABLE -DNKRO_ENABLE -DSLEEP_LED_ENABLE -DNO_SUSPEND_POWER_DOWN -DVERSION=unknown -include ./bootloader_defs.h -mthumb -DTHUMB -I. -I../../tmk_core/tool/chibios/chibios/os/license -I../../tmk_core/tool/chibios/chibios/os/common/startup/ARMCMx/compilers/GCC -I../../tmk_core/tool/chibios/chibios/os/common/startup/ARMCMx/devices/STM32F1xx -I../../tmk_core/tool/chibios/chibios/os/common/ext/CMSIS/include -I../../tmk_core/tool/chibios/chibios/os/common/ext/CMSIS/ST/STM32F1xx -I../../tmk_core/tool/chibios/chibios/os/rt/include -I../../tmk_core/tool/chibios/chibios/os/common/oslib/include -I../../tmk_core/tool/chibios/chibios/os/common/ports/ARMCMx -I../../tmk_core/tool/chibios/chibios/os/common/ports/ARMCMx/compilers/GCC -I../../tmk_core/tool/chibios/chibios/os/hal/osal/rt -I../../tmk_core/tool/chibios/chibios/os/hal/include -I../../tmk_core/tool/chibios/chibios/os/hal/ports/common/ARMCMx -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/STM32F1xx -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/CANv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/DACv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/DMAv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/EXTIv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/GPIOv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/I2Cv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/RTCv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/SDIOv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/SPIv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/TIMv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/USARTv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/USBv1 -I../../tmk_core/tool/chibios/chibios/os/hal/ports/STM32/LLD/xWDGv1 -I./boards/GENERIC_STM32_F103 -I../../tmk_core/tool/chibios/chibios/os/hal/lib/streams -I../../tmk_core/tool/chibios/chibios/os/various -I../../tmk_core -I../../tmk_core/common -I../../tmk_core/protocol/chibios -I../../tmk_core/protocol -I. ../../tmk_core/tool/chibios/chibios/os/common/startup/ARMCMx/compilers/GCC/crt0_v7m.S -o build/obj/crt0_v7m.o, ...) failed.
make (e=2):No such file or directory
make: **\* [build/obj/crt0_v7m.o] err2

**Comment by tmk** [comment]
Chibios projects have no README or instruction, not ready yet. Wait for a while, or use grep on source and cluttered documents or search on github to get info.

I guess you don't have chibios source. See tmk_core/prtocol/chibios/README.md
