### ISSUE TITLE
What is the difference between the ACTION_FUNCTION_TAP and ACTION_FUNCTION? 

### ISSUE THREAD

**Issue by chenzhihuai1990** [tmk/tmk_keyboard#369]
Hi tmk, It is an amazing project, so that I can't wait to make my keymap for my HHKB.

However, since I am not familiar with controller, I have a question about it.

Dose ACTION_FUNCTION_TAP mean that the controller will listen to the event of tapping correspond key?
In Fact, I want to implement a smart alt key as following:

1). Once `H,J,K,L` is typed with `ALT` pressed, it move the cursor as vi;
2). Once `Tab `is typed with `ALT `pressed, the switcher show up and **keep visible** until `ALT `is released;
3). Once `Alt `is tapped, it send an alt_released event(in Windows, it active the menu).

```cpp
...
[2] = ACTION_FUNCTION_TAP(ALT_FN) // assume `ALT `is mapping to FN2
...
[3] = ACTION_FUNCTION(TAB_FN)// assume Tab is mapping to FN3 in LAYER_2
...

static bool isAltTabActived=false;
void action_function(keyrecord_t *record, uint8_t id, uint8_t opt)
{
    switch (id) {
         case ALT_FN:
            if (record.event.pressed) {
                layer_on(2);
            }
            else {
                layer_off(2);
                
                if (record.tap.count>0 || isAltTabActived){
                    /*Alt released!*/
                }
                isAltTabActived=false;
            }
            
        case TAB_FN: 
            if (record.event.pressed) {
                if (!isAltTabActived){
                    isAltTabActived=true;
                    /*Alt Pressed, Tab Pressed, Tab Released*/
                }else {
                    /*Tab Pressed, Tab Released*/
                }
            }
    }
}
```

**Comment by tmk** [comment]
ACTION_FUNCTION_TAP is handled as a tap key, namely 'record->tap.count` and  'record->tap.interrupted` are available for it.
