### ISSUE TITLE
Fix OS X Recognizing keyboard as Mouse/Tablet

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#381]
interesting.

> Modified the LUFA USB HID Descriptor to change the logical/usage
minimums for System Control from 0x01 (Mouse) to 0x81 (System Power
Down), this fixes OS X recognizing the Planck as having a mouse and
tablet, even with mousekeys off.

https://github.com/jackhumbert/qmk_firmware/commit/d48a4cf1eb80600fb3e8eb859e5b77c954a18137

https://github.com/jackhumbert/qmk_firmware/issues/510

**Comment by tmk** [comment]
maybe, #74 is related to this

**Comment by exiva** [comment]
I don't have the issue referenced in #74 with the fix I did at https://github.com/jackhumbert/qmk_firmware/commit/d48a4cf1eb80600fb3e8eb859e5b77c954a18137 on a Planck.

**Comment by tmk** [comment]
@exiva Thanks!
I did cherry-pick the commit at b2d791804d some days ago.
