### ISSUE TITLE
Sun Type 5c  'Diamond' keys dead

### ISSUE THREAD

**Issue by bjd-pfq** [tmk/tmk_keyboard#384]
On a Sun Type 5c keyboard, I was using a tmk_keyboard version from January 2015.
That version happily recognized the two 'diamond' keys immediately left and right of the space bar.
I'm using Linux, and in xev these keys are reported as Hyper_L (keycode 133) and Hyper_R (keycode 134).

Now I am trying the current tmk_keyboard (on a second Sun Type 5c and a second Teensy 2.0), and this version leaves the two diamond keys stone cold dead. The 'old' teensy, when switched to this other keyboard, works fine, so the glitch must be in the software.  Same system, no reboots (in that regard, testing is a cinch).

Any hints?

**Comment by tmk** [comment]
What did you change source something?

**Comment by bjd-pfq** [comment]
No, I didn't change anything. But the one keyboard runs on tmk_keyboard from early 2015 (I think before the refactoring of the entire tree), and the other one I am testing runs on the current version of tmk_keyboard. 

Bothe keyboards are attached to the same system.  They work fine, only the newer version has the two dead keys.

In fact, I had mapped my MAGIC KEY in the old version to the combination of the l]Left and Right diamond keys. Works like a charm, but I cannot replicate this even in the sources for the current version, for I don't know and don't recall what I used for the symbols in the IS_COMMAND #define :-/ for the two diamond keys.  I perused the code today, but I cannot determine what they are.

**Comment by tmk** [comment]
Did you change Makefile to use Teensy? Now Makefile is configured for TMK converter with ATMega32u2 by default.

**Comment by bjd-pfq** [comment]
Yes, all the settings have been checked and double checked 36 times and they all are correct.

Specifically, I have, in config.h:

/*#define USE_LEGACY_KEYMAP*/

and in Makefile:

MCU = atmega32u4       # Teensy 2.0

MOUSEKEY_ENABLE = yes	# Mouse keys
EXTRAKEY_ENABLE = yes	# Audio control and System control
CONSOLE_ENABLE = yes	# Console for debug
COMMAND_ENABLE = yes    # Commands for debug and configuration
#NKRO_ENABLE = yes	# USB Nkey Rollove

But do you know what key symbols I would need for these two Diamond keys in the IS_COMMAND C-macro #define??  I cannot find any good candidates anymore in keycodes.h, but I must be overlooking some symbols.

**Comment by bjd-pfq** [comment]
Sorry, the USE_LEGACY_KEYMAP is undefined in config.h.  But it doesn't matter, I tried with and without, and it doesn't bring these keys alive in xev.

**Comment by tmk** [comment]
I just confirmed the latest code still works for me with Topre Sun keyboard.

**Comment by tmk** [comment]
yes, you can cofigure magic key with IS_COMMAND macro.

**Comment by bjd-pfq** [comment]
But which symbols do I use?  I thought it was KC_HENK and KC_MHEN but that didn't work.

Also, I think xev should at least give /some/ output, whether or not I have programmed these keys for the teensy, should it not?

**Comment by tmk** [comment]
Try getting plain the latest source code then just change MCU in  Makefile.
And `make clean` and `make` to  get firmware.

if it doesn't help, you might want to check your toolchain. I use gcc4.9.2, btw.
```
$ avr-gcc --version
avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tmk** [comment]
Sun diamond key is equivalent to Windows key or Mac Command key, which are called Gui key in TMK and USB spec. See around p59.
http://www.usb.org/developers/hidpage/Hut1_12v2.pdf

**Comment by bjd-pfq** [comment]
LGUI and RGUI, you mean.  These are defined already by default in the IS_COMMAND !
Still it doesn't work.
Let me just try a fresh new tree, like you suggest.
...
<time passes>

**Comment by bjd-pfq** [comment]
No go.  Just compiled and installed a fresh new tree, and the keys are just dead, whereas they work under the old style teensy (in fact I have both keyboards hanging off my current system :-)

The only thing I changed in all the source is MCU = atmega32u4.

Btw., I too have avr-gcc (GCC) 4.9.2.

**Comment by bjd-pfq** [comment]
Btw., I tried to recompiled,, this time having commented out USE_LEGACY_KEYMAP, and the compile
aborts with:

/home/bjd/Documents/hw/kbd/sunkbd/tmk/tmk_keyboard-master-20160918-orig/converter/sun_usb/../../tmk_core/common/keymap.c:246: undefined reference to `fn_actions'
/home/bjd/Documents/hw/kbd/sunkbd/tmk/tmk_keyboard-master-20160918-orig/converter/sun_usb/../../tmk_core/common/keymap.c:246: undefined reference to `fn_actions'
collect2: error: ld returned 1 exit status
../../tmk_core/rules.mk:550: recipe for target 'sun_usb.elf' failed
make: *** [sun_usb.elf] Error 1

**Comment by omenlabs** [comment]
I use a Sun Type 5c daily and make heavy use of the diamond (meta) keys.  It has been a while since I updated, but I can give it a shot.

**Comment by bjd-pfq** [comment]
Caveat: better use a second teensy; I'm glad I did...

**Comment by bjd-pfq** [comment]
What baffles me is that to begin with, the keys should generate at least some response from xev.
The 'old style tmk' keyboard generates this for the left and right diamond keys:

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x294, subw 0x5000002, time 396448473, (47,32), root:(1229,663),
    state 0x0, keycode 133 (keysym 0xffed, Hyper_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x294, subw 0x5000002, time 396448561, (47,32), root:(1229,663),
    state 0x40, keycode 133 (keysym 0xffed, Hyper_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

**Comment by tmk** [comment]
Gui, Diamond, Windows and Command keys are usually recognized as Super in Xorg on my site. I don't know about Hyper and Xorg key system much, though.

**Comment by omenlabs** [comment]
I just cloned and flashed and my diamond keys are working.  I'm using an m32u4 (arduino micro) and hardware serial.

**Comment by tmk** [comment]
@omenlabs Great.
BTW, I use software serial without pull-up resistors or any extra component.

**Comment by tmk** [comment]
@bjd-pfq try this hex file which is compiled with software serial for atmega32u4, it should work with teensy.
https://drive.google.com/file/d/0Bygvtwt-Y9HhOXgwOUVITThIc2s/view?usp=sharing

**Comment by omenlabs** [comment]
@tmk The timing was off enough with the software serial that my Sun Type 5c wouldn't recognize commands (according to my scope it was a small ~850us vs expected 833us per symbol).  I did the PR for hardware serial support a while back and have been using the type 5c at work ever since.

**Comment by tmk** [comment]
@bjd-pfq If you are using Xmodmap or XKB to tweak keys I guess it might cause your problem.

**Comment by bjd-pfq** [comment]
@tmk Thanks for the hex file.  Installed it, and ..... no go!
I suspect my teensy is flakey?
Everything works like a charm, all the FN keys on the left of the Sun kbd are recongized, the Help key is recognized (this is all exactly like my other compiles, btw.), but those Diamond keys remain stone cold dead.
Btw., these are two oriingal Sun Type 5c keyboards, partno. 3201234-02 for both; and both are hanigijng off of my Linux box at the moment (though I am constantly plugging off the default keyboard and power cycling the one under test, to see if that changes anything, but it doesn't).

**Comment by tmk** [comment]
@omenlabs Interesting. I tried software serial with type 5 for short period and it worked. But I will have to check its signals some later, anyway I believe  I can fix or tweak code in the end beuase sun uses very slow 1200baud signal. Maybe it needs assembly coding which requries me to learn more, fun! :D

**Comment by bjd-pfq** [comment]
No. Checked that earlier,.xmodmap is empty. Donb't call xmodmap any other way. Don't have xbindkeys or the like. 

And btw., shouldn't that affect /both/ keyboards I'm having attached to my Linux box?

**Comment by omenlabs** [comment]
I have the same part number.  Have you tried the HID listen program and debug mode?

**Comment by bjd-pfq** [comment]
The teensy runs the blink test program fine, btw., but I suspect that doesn't do much of stress testing...

**Comment by bjd-pfq** [comment]
@omenlabs Good point.  An hour ago, before this flurry of posts started, I was just running hid_listen (as root), and it produced the initial messages,, but then I couldn't get it into debug mode in any way.
Let me pick up on that..., thanks for the reminder.

**Comment by bjd-pfq** [comment]
Update:

I hooked up the 'old-style-tmk' teensy to the Sun keyboard with the dead Diamond keys.  What do you know -- still these keys are dead!

Which leads me to the conclusion there is someting amiss in this keyboard.

To verify, I hooked up the 'old-style-tmk- teensy to a /third/ Sun keyboard (same partno.).
An lo and behold, there the Diamond keys are responding correctly.

In short: the second teensy is prob. not flakey, but the second Sun keyboard itself has a flaw!
Next thing is to dissemble it, and look at the PCB and the conductive tracing for these two keys.

**Comment by bjd-pfq** [comment]
Update 2:

Lane 2 on the large membrane connector on the PCB (connecting only the two Diamond keys!) was not making contact.
I wasn't able to fix it either, so what I did was swap the entire 3-layer membrane stack + PCB from the 3rd Sun Type 5c keyboard (which was a partly cannibalized keyboard anyway) to the keyboard that was faulty.

Problem solved.

**Comment by omenlabs** [comment]
Glad you got your keyboard working again!  :-)

**Comment by bjd-pfq** [comment]
Thanks, and thanks to you and tmk for your input.

Might I add a late final question: do your ScrollLock and Compose-key LEDs light up when these keys are pressed?  Mine stay off, and only come on when the keyboards are plugged in, when they are reset, or when the MAGIC+all LEDs on is pressed.

**Comment by omenlabs** [comment]
I see the same issue with the lights not coming on.

**Comment by bjd-pfq** [comment]
Thank, I am consoled.... (double pun intended).
Maybe it should be reported as an issue?

**Comment by tmk** [comment]
I don't think Xorg/Linux usually sends signal for ScrollLock and Compose to keyboard, my desktop doesn't send for ScrollLock at least.(I don't have compose key) Try Windows 10, it seems to send for ScrollLock. Or you can xset to send the signal to keyboard.(maybe xset led on?)

If your OS support those indicators it should work. See led.c and send PR open new issue if not.

**Comment by bjd-pfq** [comment]
Ah, but both /are/ recognized by xev, so I can use them, or reprogram them (with xmodmap), etc.;
here's the xev output:

ScrollLock:
KeyRelease event, serial 37, synthetic NO, window 0x3a00001,
    root 0x294, subw 0x3a00002, time 31302858, (49,53), root:(1231,684),
    state 0x0, keycode 78 (keysym 0xff14, Scroll_Lock), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

Compose:
KeyPress event, serial 37, synthetic NO, window 0x3a00001,
    root 0x294, subw 0x3a00002, time 31308714, (49,53), root:(1231,684),
    state 0x0, keycode 135 (keysym 0xff67, Menu), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

**Comment by tmk** [comment]
First, indicator status is generally controlled by OS/host, not keyboard(or converter). If your OS doesn't controll them LEDs doesn't lit. And Linux/Xorg doesn't seem to controll indicators for those keys. Again try WIndows or xset.

Can you compose charactor with your "compose" key? I tried to setup compose key on xfce4/Ubuntu16.04 and xev recognizes it as 'Multi_key', not 'Menu' and I can compose now. But Xorg still doesn't handle indicator of compose.

I think indicators of compose and scrollLock are lit on with 'xset led on', did you try it?

**Comment by bjd-pfq** [comment]
Yes, that works, although oddly enough not ever for CapsLock or NumLock.
and only numerically for Compose (reported by xev as Menu):

xset led 3		sets ScrollLock    works
xset led 5		sets Compose      works

xset led named "Scroll Lock"    works
xset led named "Menu"               xset: Invalid led name: Menu

I suppose you can program Compose to use as a compose-key; but I have been using the one right next to it, AltGraph, for that purpose some time.   Strangely, since you mentioned 'Multi-key', my AltGraph-key is reported by xev as 'Multi-key' (which indeed more or less is synonym with 'compose').

**Comment by bjd-pfq** [comment]
In Linux Mint, which I am using, I have not done anything special for the keyboard, not in the cinnamon-settings, not in xmodmap or any other way.  But I have a feeling that in this default setup there are some misnomers.  The Compose key (with the word Compose on it, and it has a led) should more appropriately be called 'Multi-key'.  And AltGraph?  I don't know.

I do know there is an option in the keyboard settings 'Maintain Key compatibility with old Solaris keycodes'.
I haven't turned that on yet, but I am going to try it next, to see what difference if any that makes.

**Comment by tmk** [comment]
Great, the converter supports all indicators! No issue there.

Yes,  I just read this and configure my compose(Menu) key as 'Compose key(Multi key)' on Xorg.
https://help.ubuntu.com/community/ComposeKey

How those indicators are handled depends fully on your host(OS), you may configure them or not.
I never used actually Compose key and AltGr before and don't know much. You will get more help from Mint community.
