### ISSUE TITLE
logical error in xt_usb/matrix.c

### ISSUE THREAD

**Issue by bjd-pfq** [tmk/tmk_keyboard#405]
*** xt_usb/matrix.c.orig	2016-11-09 18:28:36.263834630 +0100
--- xt_usb/matrix.c	2016-11-09 18:28:57.315882187 +0100
***************
*** 162,186 ****
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;
--- 162,186 ----
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7_E0;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;

**Comment by bjd-pfq** [comment]
Sorry, hope this looks more like code:

`*** xt_usb/matrix.c.orig	2016-11-09 18:28:36.263834630 +0100
--- xt_usb/matrix.c	2016-11-09 18:28:57.315882187 +0100
***************
*** 162,186 ****
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;
--- 162,186 ----
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7_E0;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;
`

**Comment by bjd-pfq** [comment]
`*** xt_usb/matrix.c.orig	2016-11-09 18:28:36.263834630 +0100
--- xt_usb/matrix.c	2016-11-09 18:28:57.315882187 +0100
***************
*** 162,186 ****
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;
--- 162,186 ----
                  state = E0_2A_E0;
              else
                  state = INIT;
              break;
          case E0_2A_E0:
              if(code == 0x37)
                  matrix_make(PRINT_SCREEN);
              else
                  state = INIT;
              break;
          case E0_B7:
              if(code == 0xE0)
!                 state = E0_B7_E0;
              else
                  state = INIT;
              break;
          case E0_B7_E0:
            if(code == 0xAA)
                matrix_break(PRINT_SCREEN);
            else
                state = INIT;
            break;
          case E1:
              if (code == 0x1D)
                  state = E1_1D;
`

**Comment by acid2000** [comment]
Could you put some more information here

**Comment by tmk** [comment]
This is not applicable anymore and the current code base has no issue related to this.
