### ISSUE TITLE
AEKII missing left and right arrow keys presses (ADB->USB)

### ISSUE THREAD

**Issue by 128keaton** [tmk/tmk_keyboard#412]
I'm having a very strange issue that manifests itself in both Windows and OS X. Every couple of left or right arrow key presses, the OS doesn't respond to the presses. I checked with the hid_listen and it proved that its something with the adaptor. I don't have anything to test the keyboard with sadly, but I am using the stock ADB cable.

**Comment by tmk** [comment]
>  I checked with the hid_listen and it proved that its something with the adaptor.

You mean, hid_listen shows your converter recognizes the *missing* key press from keyboard but it fails to send it to PC? Or your converter doesn't recognize the key press at all?

**Comment by 128keaton** [comment]
@tmk the converter doesn't recognize the keys

**Comment by tmk** [comment]
OK. Then I'd recommend to replace switch on the keys, first.
