### ISSUE TITLE
MODS_TAP_KEY: modifier key doesn

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#422]
`ACTION_MODS_TAP_KEY(MOD_LALT, KC_LGUI)` doesn't register `LGUI`, always spits out `LALT`.
It seems like tapping logic is iffy in aciton_tapping.c.

**Comment by tmk** [comment]
Tested with this keymap: https://goo.gl/vifUWG

**Comment by pnit** [comment]
The last change broke converter/usb-usb by removing the define for IS_ANY

**Comment by tmk** [comment]
oops, thanks. I'll fix it later.

**Comment by tmk** [comment]
Fixed at commit be80ed2ef3ca669cc8dcc3555c09da0a7defae8c
