### ISSUE TITLE
Feature Request: Individual Keycodes for symbols

### ISSUE THREAD

**Issue by apierz** [tmk/tmk_keyboard#432]
If there were individual keycodes for symbols like ( or } they could be used with dual role keys. For example I could set my left shift button to work like a normal shift button when held but output a ( when tapped and the same for my right shift button, but it would output a ).

Currently, I don't think there is a way to access characters that require a modifier to be pressed for dual role keys.

**Comment by DreymaR** [comment]
Wrong way of thinking, I'm afraid. Key codes are codes for pressing a key. Input events are what the OS creates as a result of you pressing keys or other things that generates "key presses". The only truly dual role key I know of is Pause/Break which actually sends different key codes depending on shift state AFAIK. But it's weird. ;-)

You'll find another open issue about sending Unicode, if that's what you want; the solution will be OS dependent and a bit clunky.

If you want an a-or-Shift button, that's possible. You want this, as an action for your Shift key:
```
ACTION_MODS_TAP_KEY(MOD_LSFT, KC_A)
```
