### ISSUE TITLE
Power management keys may not work

### ISSUE THREAD

**Issue by eltang** [tmk/tmk_keyboard#435]
See qmk/qmk_firmware#900.

**Comment by eltang** [comment]
Might [this descriptor](https://github.com/kiibohd/controller/blob/master/Output/pjrcUSB/arm/usb_desc.c#L270) work?

**Comment by tmk** [comment]
Not sure. It would be nice if you can try it.

BTW, I confirmed System control keys like Power Down(0x81) and Sleep(0x82) don't work on WIndows10 at this point. 0575b3db2e825fdf9d77f6cf83f6ecd9626cf59a
On Linux they work well, I don't know on Mac.

**Comment by eltang** [comment]
Those were the keys I was concerned about.

**Comment by tmk** [comment]
we need this fix too.
https://github.com/qmk/qmk_firmware/pull/963
