### ISSUE TITLE
Converters based on Teensy 3.6?

### ISSUE THREAD

**Issue by DreymaR** [tmk/tmk_keyboard#443]
Can a TMK-powered USB-USB or PS2-USB converter use the new Teensy 3.6 (or 3.5)? It's such a powerhouse, it'd hold a whole world of hotstrings and goodness.

**Comment by tmk** [comment]
PS2-USB will work, just check its I/O supports 5V. What you have to do is only writing code to implement `tmk_core/protocol/ps2_io.h` for the controller, see AVR implementation `tmk_core/protocol/ps2_io_avr.c` for example.

As for USB-USB you will have to rewrite most of codes yourself, it is more difficult.
