### ISSUE TITLE
Add avr-libc to build.md Linux toolchain section

### ISSUE THREAD

**Issue by bekwam** [tmk/tmk_keyboard#453]
My Ubuntu 16.04 needed a followup apt-get after the gcc-avr package to build

apt-get install avr-libc

**Comment by tmk** [comment]
Sorry for late reply. hmm, I couldn't find which document I should fix.

https://github.com/tmk/tmk_keyboard/wiki/Bash-On-Ubuntu-On-Windows10#install-tools
this includes `avr-libc`, somewhere else?
let me know if you still remember.

**Comment by bekwam** [comment]
Hi,

I see the command on the Ubuntu/Windows 10 page.  I was following this page and it built so quickly I didn't look over the rest of the Wiki!

https://github.com/tmk/tmk_keyboard/wiki/Build-firmware-on-VirtualBox
