### ISSUE TITLE
Where can I find the function for ACTION_LAYER_TAP_KEY(mods, key)

### ISSUE THREAD

**Issue by dunkarooftop** [tmk/tmk_keyboard#459]
I am trying to hack it so when I tap a key can display ```_``` which is ```SHIFT  + MINUS``` and when held go to X Layer. Unless there is a easier way please let me know too :)

I don't think I can put ```SHIFT``` into ```key``` of ```ACTION_LAYER_TAP_KEY(mods, key)```

Thanks !

**Comment by tmk** [comment]
first check action_code.h to know how it is defined and see action.c to know definition of the action.

**Comment by dunkarooftop** [comment]
Thank you !!
