### ISSUE TITLE
keymap editor doesn't work with Safari

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#460]
send PR for this issue or donate mac to me.

**Comment by pyro2927** [comment]
Is there more information on this? I'd like to help, but using Safari 10.1.1 everything seems to work fine.  I got a hex file that diff'd identical to one made in Chrome.

**Comment by tmk** [comment]
Thanks for the help. oh, great. It is good to hear that it works with that version at least.

I can't remember what is actually problem but some users reported it had problem with Safari.
