### ISSUE TITLE
Request to continue writing the BlueFruit

### ISSUE THREAD

**Issue by zouzhe1** [tmk/tmk_keyboard#465]
The ble hid is the function that everybody likes............

**Comment by tmk** [comment]
I think code for bluefruit is still there. what do you mean?
https://github.com/tmk/tmk_keyboard/tree/master/tmk_core/protocol/bluefruit

**Comment by zouzhe1** [comment]
I saw this code，but I don't know how to use this code，for example，the GH60，how to configure it to support bluefruit？thanks.

**Comment by tmk** [comment]
I dont' know how it works, to be honest. But you can consult with these resources.
https://github.com/tmk/tmk_keyboard/tree/master/orphan/terminal_bluefruit
https://learn.adafruit.com/convert-your-model-m-keyboard-to-bluetooth-with-bluefruit-ez-key-hid/overview
