### ISSUE TITLE
Building for KEYMAP_M0116_ANSI

### ISSUE THREAD

**Issue by scramble45** [tmk/tmk_keyboard#470]
I want to specify using the KEYMAP_M0116_ANSI found in keymap_common.h. How do I specify it?

make [KEYMAP=KEYMAP_M0116_ANSI] doesn't work.

I know doing something obviously wrong.

**Comment by scramble45** [comment]
Would something like this work?

```make -f Makefile.teensy [KEYMAP=M0116.c]```


[M0116.c](https://gist.github.com/scramble45/1a86aa77d558537299aac5c8fa504223)

**Comment by tmk** [comment]
use keymap_m0116.c as file name and add `KEYMAP=m0116` to make command.
