### ISSUE TITLE
Is possible make a 1x16 pad without a diode matrix?

### ISSUE THREAD

**Issue by YCF** [tmk/tmk_keyboard#473]
I'm making a 4x4 numpad with 32u4.As we know,32u4 have enough io to connect each key.
so,How to configure the matrix.c ?

Inspired by:
https://www.reddit.com/r/MechanicalKeyboards/comments/66588f/wireless_split_qmk_mitosis/dggoepg/

**Comment by tmk** [comment]
Just check 16 pins and return their state.  You don't have to have row line.

**Comment by YCF** [comment]
row to GND or VCC,which is better?

**Comment by tmk** [comment]
GND.

ah, i checked  the link now, if low power consumption matters for this  I think you better have a pin for the row and make high when idle.

**Comment by YCF** [comment]
4x4 matrix
vs 
16 io

how about the CPU utility？

**Comment by tmk** [comment]
i guess 1x16 is lighter in cpu load.

2017/05/28 19:59 "YouCanFly" <notifications@github.com>:

**Comment by YCF** [comment]
I don't care  about the power matter，I just  want to kill the diodes,so we don't have to solder it.
;p
