### ISSUE TITLE
ChibiOS version to use

### ISSUE THREAD

**Issue by mtfurlan** [tmk/tmk_keyboard#490]
So right now the documentation for getting ChibiOS is inconsistent, and sometimes wrong.
The instructions in `teensey_lc_onekey` say to clone ChibiOS into `tmk_core/tool/chibios/ChibiOS`, and "This should be it", but a few days ago the master branch of ChibiOS didn't compile, so I checked out the most recent stable branch and it was fine.

All of the instructions I can find:
- https://github.com/tmk/tmk_keyboard/blob/master/keyboard/teensy_lc_onekey/instructions.md
- https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/protocol/chibios/README.md
- https://github.com/tmk/tmk_keyboard/blob/master/keyboard/infinity_chibios/MEMO.txt

The first two just say to clone the official chibios and chibios-contrib into their directories in `tmk_core/tool/chibios/`, which as mentioned doesn't compile.

`infinity_chibios` says to use the `kinectis` branch, from https://github.com/flabbergast/ChibiOS.git, and not to use chibios-contrib.

How should all of this documentation be unified?
https://github.com/tmk/tmk_core/pull/8 suggests that it should just be specified on a per-project basis, so like for `teenskey_lc_onekey` maybe the instructions should be something like 

> clone https://github.com/ChibiOS/ChibiOS somewhere
> checkout branch stable_17.6.x or whatever
> set `CHIBIOS` to that directory in your makefile

The per-project instructions also make sense cause `infinity_chibios` uses a very different version, and I'm doubtful it'll be reconciled.

**Comment by tmk** [comment]
Yes, we should have 'how to setup ChibiOS' at just one place to avoid confusion,  and that part should be removed from the other two  docs. Good palce is `tmk_core/protocol/chibios/README.md` or wiki.

TMK should  work with latest stable of ChibiOS and keep up with master branch as possible hopefully.

`infinity_chibios` should work with official repo, its document is just old and not updated.
