### ISSUE TITLE
Enable tmk_core debug printing?

### ISSUE THREAD

**Issue by kaihuang201** [tmk/tmk_keyboard#495]
How do I enable tmk_core debug print?

**Comment by tmk** [comment]
Set these variables to true somewhere.

https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/debug.h#L49-L53

**Comment by kaihuang201** [comment]
This still doesn't enable debug print that are inside **tmk_core**.

**Comment by tmk** [comment]
Which one for example?

**Comment by tmk** [comment]
And this may help?
https://github.com/tmk/tmk_keyboard/wiki/FAQ#debug-console

**Comment by kaihuang201** [comment]
For example: https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/action_tapping.c#L42

My debug console works fine. It shows `Listening:` and `Keyboard starting`. And `dprintf` in `matrix.c` shows up as intended. But I can't see anything in tmk_core, unless I add `dprintf` myself.

**Comment by tmk** [comment]
To enable debug print there you have to define `DEBUG_ACTION` somewhere, for example at line before these lines, or also you can define in your makefile.
https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/action_tapping.c#L9-L13
