### ISSUE TITLE
inline declarations in matrix.c aren't being used

### ISSUE THREAD

**Issue by TD22057** [tmk/tmk_keyboard#51]
Most of the keyboard/*/matrix.c files declare functions like this:

````
inline
bool matrix_is_on(uint8_t row, uint8_t col)
{
    return (matrix[row] & (1<<col));
}
````

but the header file matrix.h declares the function as:

````
bool matrix_is_on(uint8_t row, uint8_t col)
````

So there is no inline'ing happening anywhere.  It might inline in matrix.c but maybe only for code after the function code.  

I suggest removing these inline statements as they are misleading since it isn't really inline'ing anything.  FYI - I did quick test with putting the code in the matrix.h header to it will inline properly and it makes almost no difference in the speed at which matrix_scan() is called (1% faster).  

For a full discussion on inline strategies, see: http://www.greenend.org.uk/rjk/tech/inline.html

**Comment by youxiaojie** [comment]
tmk_core/common/matrix.h
#define MATRIX_IS_ON(row, col) (matrix_get_row(row) && (1<<col))
there is a macro in matrix.h, why define a function again?
