### ISSUE TITLE
Wiki reports Teensy2.0++ as AT90USB126

### ISSUE THREAD

**Issue by Svalorzen** [tmk/tmk_keyboard#512]
I'm sorry, I'm not an expert. I just noticed that the page "Compatible Microcontrollers" reports the Teensy 2.0++ as "AT90USB126", while the page "https://www.pjrc.com/teensy/" reports it as "AT90USB1286".

The wiki page also lists AT90USB1286 as a possible thing that should work, so I'm not sure whether they are the same. I tried googling for just for the 126 version, but I didn't find anything. I'm not sure whether this is an error, so I just wanted to let you know.

**Comment by tmk** [comment]
Fixed. Thanks!
