### ISSUE TITLE
Persistent compiler warnings

### ISSUE THREAD

**Issue by DreymaR** [tmk/tmk_keyboard#515]
When compiling TMK layouts (for the USB-USB converter), I keep getting these compiler warnings:
```
../../tmk_core/common/keyboard.c: In function ‘keyboard_task’:
../../tmk_core/common/keyboard.c:151:1: warning: label ‘MATRIX_LOOP_END’ defined but not used [-Wunused-label]
 MATRIX_LOOP_END:
 ^
../../tmk_core/common/avr/suspend.c:73:13: warning: ‘standby’ defined but not used [-Wunused-function]
 static void standby(void)
```

I realize that they aren't harmful, but are they necessary? They are confusing and annoying, especially for new users.

If these definitions are necessary in some cases but not in others, maybe we could work some directive magic to avoid this behavior? Some `#ifdef` funky stuff or suchlike.

**Comment by tmk** [comment]
Fixed. Thanks
