### ISSUE TITLE
VUSB: undefined references

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#547]
`keyboard_protocol` and `keyboard_idle` of host.h are not defined in VUSB protocol. Those are referenced from command.c and cause linker error #546.

https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/command.c#L337-L338

**Comment by jpmorris** [comment]
Getting this same error for massdrop/ctrl even with VUSB ifdef.

**Comment by tmk** [comment]
Fixed with 6271878.
