### ISSUE TITLE
AC_BOOTLOADER(BTLD) doesn't work

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#557]
Action 'Jump to Bootlloader' doesn't work in Actionmap and Unimap while `KC_BOOTLOADER(BTLD)` still works in Keymap.

It is currently defined for Keymap here but the action should be defined in action.c specifically in `register_code()`.
https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/keymap.c#L157-L161

Also `ACTION_KEY(KC_BOOTLOADER)` may not be optimal. Action codes including `ACTION_COMMAND()` and `ACTION_FUNCITON()` should be reorganized.
https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/common/actionmap.h#L287

**Comment by RaoulDuke-Esq** [comment]
Using TMK Keycap Editor:
BLTD works for my M122 (IBMPC-USB Converter(ATmega32U4) - 122-key Terminal)
BLTD does not work for my Pingmaster (IBM4704-USB Converter rev.1 for Alps 102-key).  I have tried it in several positions on the board but it never works.

**Comment by tmk** [comment]
`AC_BOOTLOADER` and `AC_BTLD` works now.
- 83b90f4b6fe67
