### ISSUE TITLE
Testing GH60 firmware without PCB

### ISSUE THREAD

**Issue by selir27** [tmk/tmk_keyboard#56]
Hi,
I am trying to make NKRO keyboard. It uses keyboard matrix with soldered wires instead of PCB board (as in the project http://blog.fsck.com/2013/04/index.html). I want to use or to modify the gh60 firmware for my needs. Is it possible to test the firmware with only one key? I am not sure that I will connect right all the wires of my matrix form the first time. I would like to minimize the errors. So I would like to know if the software works fine before I make the hardware part. It seems that the firmware scans for the matrix, but I am not sure if it will works with only one key connected to atmel AVR board (arduino micro in my case).

**Comment by mikeshandssay** [comment]
Onekey is not compiling for me on OS X 

avr-gcc (GCC) 6.2.0

```
obj_onekey_lufa/common/keymap.o: In function `keymap_key_to_keycode':
/Users/mhiggins/projects/tmk_keyboard/keyboard/onekey/../../tmk_core/common/keymap.c:236: undefined reference to `keymaps'
```

```
obj_onekey_lufa/common/keymap.o: In function `keymap_fn_to_action':
/Users/mhiggins/projects/tmk_keyboard/keyboard/onekey/../../tmk_core/common/keymap.c:246: undefined reference to `fn_actions'
```

**Comment by tmk** [comment]
Hmm, maybe  gcc version? Ive used 4.9 iirc and never tried with 6.

Checked binutil version? See caveats.
https://gcc.gnu.org/gcc-6/changes.html

Or just use other older versions if possible.

**Comment by mikeshandssay** [comment]
@ TMK, the same occurred with 4.8. We are both talking on GH and can resolve it there.

If we DO need specific versions to build... do we know the ones to install on vanilla Ubuntu?

**Comment by tmk** [comment]
Confirmed.
Remove both 'static' keywords from keymap.c.

I'll look into other places too and update them later.
