### ISSUE TITLE
Inputting accent

### ISSUE THREAD

**Issue by LouWii** [tmk/tmk_keyboard#569]
Hi there,

I'm looking at modifying TMK so I can input accent letters like ù à é è on a US keyboard. Is that even doable? I'm kind of skeptical as I think this is handled at the OS level and not the keyboard, but I want to be sure. I found no information at all regarding the subject.

Thanks

**Comment by tmk** [comment]
You're right, how to input those characters depends totally on keyboard layout on OS.
This may be helpful.
https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#input-special-charactors-other-than-ascii-like-c%C3%A9dille-%C3%87
