### ISSUE TITLE
Modifier question - Make LALT + TAB = LCTL + TAB.

### ISSUE THREAD

**Issue by jackiefoyer** [tmk/tmk_keyboard#572]
Hello again - having a lot of fun programming my keyboard!

I would like to change the behavior of LALT + TAB to be LCTL + TAB, but all other actions with LALT to remain the same. Is this possible, and what is the best way to achieve this?

Thank you for your help!

**Comment by DreymaR** [comment]
In my TMK files, I have an example of action functions turning modifiers into more advanced ones. I think your best bet in this case is an action function, since you want the key to perform normally except in one circumstance.

https://github.com/DreymaR/BigBagKbdTrixTMK/tree/master/_myunimaps
