### ISSUE TITLE
Set Japanese Thumb Modifiers to CTRL

### ISSUE THREAD

**Issue by limeb** [tmk/tmk_keyboard#575]
I type on a JIS keyboard layout with the thumb keys set to control.
This allows me to hit control modifiers with out leaving the home row on the keyboard.

Is there any feasible way to get this work?

I would like to set 007B and 0079 on the keyboard to be ctrl maybe using this tool if possible.

**Comment by tmk** [comment]
I believe this can remap them. Let me know if not.

**Comment by tmk** [comment]
To be honest, I'm not sure what you are trying, but if you want to send ctrl key the #128 doesn't affect.
Just use normal 6KRO instead of NKRO if you suffer from the issue.

what are you meaning by 007B and 0079?
