### ISSUE TITLE
Command.h doesn't have correct include guard

### ISSUE THREAD

**Issue by drashna** [tmk/tmk_keyboard#580]
This was found in QMK, and we checked TMK just to make sure....

https://github.com/tmk/tmk_keyboard/blob/00f5ed3210e1241da04b7c6970bb53ce912cf3f4/tmk_core/common/command.h#L18-L19

This should be:
```c
#ifndef COMMAND_H
#define COMMAND_H
```

Not sure this breaks anything, but ....

**Comment by tmk** [comment]
Thanks for reporting.
