### ISSUE TITLE
It's not possible to get momentary switch to layer lower than current.

### ISSUE THREAD

**Issue by cub-uanic** [tmk/tmk_keyboard#59]
It's not possible to get momentary switch to layer lower than current.

Following explanation is based on my own fork, specifically on file https://github.com/cub-uanic/tmk_keyboard/blob/cub_layout/keyboard/ergodox/keymap_cub.h

For example, when I'm hold FN6 or tap FN2, and layer 2 is active, then tap on FN1 does nothing, but FN3 and FN4 does momentary layer switch as expected.
Or other example: when I hold FN3 and layer 3 is active, then FN6 and FN1 does not work, but FN4 does momentary layer switch as expected and FN6 does layer switch as well.

I think this is bug in TMK itself, somewhere around momentary switching, and it's triggered only when layer number used in ACTION_LAYER_MOMENTARY macro is less than currently active layer. Macro ACTION_LAYER_SET works as expected (see 'other example' about working FN6).

Also, see forum discussion here: http://geekhack.org/index.php?topic=48106.msg1042480#msg1042480

**Comment by Eric-L-T** [comment]
I think I have discovered a workaround involving a very complex macro. Is anyone interested?

**Comment by cub-uanic** [comment]
Of course, please share

**Comment by Eric-L-T** [comment]
Here is what I could throw together:
    case 0:
        if (record->event.pressed) {
        	if (biton32(layer_state) == 1) {
        		layer_off(1);
        	} else if (!biton32(layer_state)) {
            	layer_on(1);
     	    }
        } else {
        	if (biton32(layer_state) == 1) {
        		layer_off(1);
        	} else if (!biton32(layer_state)) {
            	layer_on(1);
     	    }
        }
    break;
.
