### ISSUE TITLE
Can't compile TMK - ./halconf_community.h: No such file or directory

### ISSUE THREAD

**Issue by lebastaq** [tmk/tmk_keyboard#597]
Hey guys,

I'm having trouble compiling TMK for my Teensy 3.2

I followed the instructions:

- Cloned TMK
- Cloned Chibios into tmk_core/tools/chibios/ChibiOs
- Cloned Chibios contrib into tmk_core/tools/chibios/ChibiOs-Contrib

Went into folder keyboards/teensy3.2_tkl and make

I'm getting a 'no such file or directory' for ./halfconf_community.h

Here's the error log:
[https://pastebin.com/BHEizVwC](pastebin)

Does anyone have some hinsight ?
So far it's been a difficult process

Thanks
Cheers

**Comment by lebastaq** [comment]
Followed these instructions https://github.com/qmk/qmk_firmware/blob/master/keyboards/chibios_test/teensy_lc_onekey/instructions.md

Started a new project using the console and copied over the teensy 3.2 configuration:


`MCU = cortex-m4
F_CPU = 16000000
MCU_FAMILY = KINETIS
MCU_SERIES = K20x
MCU_STARTUP = k20x7
BOARD = PJRC_TEENSY_3_1
ARMV = 7`

Still not working, but getting closer...

**Comment by SkyCoops** [comment]
Hello @lebastaq, have you find a solution yet?

I am encoutering the same problem. Any help would be appreciated.

**Comment by lebastaq** [comment]
Hey,

I didn't find a solution.
Instead, I bought a pro micro and used QMK

Best regards

**Comment by SkyCoops** [comment]
That's very unfortunate.

I am feeling that I have to get a pro micro since it is the standard here.

Let's desolder everything...

Thank you, regards
