### ISSUE TITLE
which method we take？

### ISSUE THREAD

**Issue by youxiaojie** [tmk/tmk_keyboard#598]
USB NKRO methods
----------------
1. Virtual keyboards
    Keyboard can increase its KRO by using virtual keyboards with Standard or Extended report.
    If the keyboard has 2 virtual keyboard with Standard report(6KRO), it gets 12KRO.
    Using this method means the keyboard is a composite device.

2. Extended report
    It needs large report size for this method to achieve NKRO.
    If a keyboard has 101keys, it needs 103byte report. It seems to be inefficient.

3. Bitmap report
    If the keyboard has less than 128keys, 16byte report will be enough for NKRO.
    The 16byte report seems to be reasonable cost to get NKRO.

**Comment by tmk** [comment]
it is definitely 3.
