### ISSUE TITLE
Incoherent behaviour with two M0110s and a M0110A

### ISSUE THREAD

**Issue by skagon** [tmk/tmk_keyboard#6]
I've got three early Mac keyboards here. As title states, two M0110 (plain vanilla Mac) and one M0110A (Mac Plus).
The problem is, apart from the M0110A not working properly, which is to be expected, that one of the 0110s and specifically the (sort of) newer one works perfectly, while the second, older, one is exhibiting delays, i.e. keypresses arrive slowly. The 0110A is even worse in that respect. I'm using plain vanilla code with Teensy 2.0.
Let me explain in greater detail.
Using HID_listen, I tried to analyse the behaviour of each of the keyboards.
M0110 new:
- upon connection of the keyboard (I mean the "phone" jack, not teensy USB), no errors
- upon disconnection of the keyboard, no errors again
- keys get transferred almost instantaneously (as they should)

M0110 old:
- upon connection of the keyboard, there's a series of errors, usually a series of send error 03 immediately followed by receive error 04; rarely, receive error 02
- upon disconnection, same thing: 03 04 03 04 03 04 03 04 and sometimes 02
- keys lag registering both key press and release; lag for each is around 0.4 second +/- 0.25sec
- randomly, there's a "received data FF" between key events
- rarely, a key release will not register, causing the system to think a key is pressed down

M0110A:
- upon connection of the keyboard, there's a series of errors, usually a series of send error 03 immediately followed by receive error 04; rarely, receive error 02
- upon disconnection, same thing: 03 04 03 04 03 04 03 04 and sometimes 02
- keys lag registering both key press and release; lag is around 0.9 second +/- 0.5sec (for _each_ event; i.e. press and release usually last for more than 1.5secs)

I have to add that the M0110A keyboard has been thoroughly cleaned (after first connecting it and seeing the huge lag), all keys have been checked with a continuity metre and are working perfectly (and switch instantly), all lines from the keyboard microcontroller have been checked and double-checked for shorts and there's no problem there either.
On the other hand, the working M0110 hasn't been cleaned nor checked in any way, apart from replacing a couple of keys, and it was working perfectly even before that (well, apart from the aforementioned couple of problematic keys).
The cables all work perfectly. Yes, I checked them.

I'm wondering whether it's a problem with the timings, but from what I can see, all data 'events' in the code are not reliant on timing, timing is there just as a time-out, not a latch trigger.
I was also wondering whether it could be a problem with the matrix overloading, but again, I can't see the connection in the code.
I'll try to relax the timings and see if that helps any. In the meantime, please, don't hesitate to offer advice!
Thanks!

**Comment by cuavas** [comment]
Sorry for bumping a dead issue, but @skagon would you be so kind as to post good quality photos of the PCB from M0110A keyboard?  I recently added emulation of this keyboard to MAME, guessing all the details from the microcontroller program.  I’d like to know what the exact microcontroller model is, what kind of clock source it uses, and whether is it has watchdog circuitry.
