### ISSUE TITLE
 #define MATRIX_IS_ON(row, col) (matrix_get_row(row) && (1<<col)) vs inline bool matrix_is_on(uint8_t row, uint8_t col)

### ISSUE THREAD

**Issue by youxiaojie** [tmk/tmk_keyboard#601]
in tmk_core/common/matrix.h
#define MATRIX_IS_ON(row, col) (matrix_get_row(row) && (1<<col))
there is a macro in matrix.h, why define a function again in /convter/ps2_usb/matrix.c?
```
inline bool matrix_is_on(uint8_t row, uint8_t col)
{
    return (matrix[row] & (1<<col));
}

```

**Comment by tmk** [comment]
`MATRIX_IS_ON` doesn't seems to be used and can be removed.
I thought it was useful but not used for some reason.
