### ISSUE TITLE
Add link[wiki/keymap-examples] to homepage (readme).

### ISSUE THREAD

**Issue by chenzhihuai1990** [tmk/tmk_keyboard#605]
Add [wiki/keymap-examples](https://github.com/tmk/tmk_keyboard/wiki/Keymap-examples) to homepage [readme](https://github.com/tmk/tmk_keyboard/). In order to let more people share their idea.

I have just found that there is a page for us to share our example, I have just added my own (smartalt). I think this page is hard to found out, why not add a link to it in homepage?

**Comment by tmk** [comment]
it seems to be good idea. I will do.

**Comment by GianniGi** [comment]
In the page https://github.com/tmk/tmk_keyboard/wiki/Keymap-examples
there are many non working links. Every link should instead point to GitHub. You can link the author page for attribution, but you mix mirror everything in GitHub.

For example this link doesn't work anymore
"Reverse-shifted for numbers"

**Comment by tmk** [comment]
Note that you can edit wiki page. 
Feel free to edit the page to correct them for the community!

Thank you
