### ISSUE TITLE
Two FN keys holding issue

### ISSUE THREAD

**Issue by anjari** [tmk/tmk_keyboard#611]
It's hard to describe it so I will just show the steps to produce the issue:

1) Assume you have mapped FN + W/A/S/D as arrow keys, and you have two FN keys.

2) Hold 1st FN, then press W/A/S/D keys. It will function as arrow keys as expected.

3) While 1st FN still being held, hold the 2nd FN key.

4) Then press the W/A/S/D keys. It still functions as arrow keys.

5) Relese the 1st FN (note that the 2nd FN key is still being held)

6) Then press the W/A/S/D keys. This time the arrow keys don't work, it will produce normal w/a/s/d letters.

Expected result: since the 2nd FN key is still being held, pressing W/A/S/D keys should still function as arrow keys.

I also found this issue in QMK firmware.

FYI I'm using KBParadise V60 Type R polestar edition keyboard.

**Comment by tmk** [comment]
This is result of my current keymap design and won't be fixed.
This can happen also on normal keys like 'a', not only layer keys.

You will need to define two equivalent layers with two different layer keys to get "Expected result".

See explanation there also.
https://github.com/qmk/qmk_firmware/issues/5544
