### ISSUE TITLE
Increasing max amount of layers

### ISSUE THREAD

**Issue by bash-d** [tmk/tmk_keyboard#639]
I am unable to compile any unimap keymaps that have more than 8 layers, and am unable to figure out what I need to change in order to increase the maximum.

**Comment by tmk** [comment]
Show us your code and error message from compiler.

I think you can define up to 32 layers as long as you have program memory.

**Comment by bash-d** [comment]
Turns out I was just being an idiot and using UNIMAP_PS2 for each one of my layers instead of just UNIMAP for my ps2_usb keymap.
