### ISSUE TITLE
English Correction PR

### ISSUE THREAD

**Issue by oliverdelancey** [tmk/tmk_keyboard#667]
First of all, I want to say what an awesome project this is! The documentation is extremely thorough and there is an impressive set of features.

Anyway, would you be willing to accept a PR with English corrections in the README's? It would add a polish to how the project looks. The writing is technically acceptable English, but there are a couple phrases and sentence structures that are not idiomatic English. Note that I haven't started anything yet, just asking if you would accept such a PR if I were to do this.

**Comment by tmk** [comment]
Thank you for your suggestion.
Yes, I'm happy to accept corrections. 

Which README? I tend not to update documents so often, due to my laziness.
One in top directory is too old at least and it should be updated by me before applying corrections from you.

**Comment by oliversandli** [comment]
It's nothing serious. Mostly just missing articles (a, an, the), punctuation, and the occasional run-on sentence. I can start working on the PR before or after you rework the main README; whatever works best for you.

**Comment by oliversandli** [comment]
I didn't take a look at _all_ the README's, but most that I read had possible improvements.

**Comment by tmk** [comment]
OK. Could you make PR?

I can't get clear idea on how README should be updated at this time, I'll do it later.
Thanks

**Comment by oliversandli** [comment]
Ok, thanks! I'll start on a PR. It will take at week at most.

**Comment by oliversandli** [comment]
Hehe, after starting work it looks like it might take more like 2 weeks. Sorry for the initial incorrect estimate!

**Comment by tmk** [comment]
No rush at all. Take time!

I think it would be nice to start with small PR, rather than one big PR.
This will save our time in case that we have different preference for somehting.
