### ISSUE TITLE
Kensington Turbo 5 Mapping

### ISSUE THREAD

**Issue by BosungLim** [tmk/tmk_keyboard#677]
I am using Turbo 5 and wondered if we can change the mouse button mapping. It will be great if it can make the scroll function.

**Comment by tmk** [comment]
You can do with tools on computer like xmodmap and xbindkeys, though, it is still nice idea. PR would be appreciated.

For someone who want to try scroll function,
ps2_mouse has codes for the function:
https://github.com/tmk/tmk_keyboard/blob/6360eb308c4b81d5effde77e9b0f357dd9673696/tmk_core/protocol/ps2_mouse.c#L124-L160

You can apply this code into `adb_mouse_task()` in `matrix.c` of adb_usb probably.

**Comment by BosungLim** [comment]
> You can do with tools on computer like xmodmap and xbindkeys, though, it is still nice idea. PR would be appreciated.
> 
> For someone who want to try scroll function,
> ps2_mouse has codes for the function:
> https://github.com/tmk/tmk_keyboard/blob/6360eb308c4b81d5effde77e9b0f357dd9673696/tmk_core/protocol/ps2_mouse.c#L124-L160
> 
> You can apply this code into `adb_mouse_task()` in `matrix.c` of adb_usb probably.

**Comment by BosungLim** [comment]
sorry, I had closed the issue by a mistake and reopened it.

anyway, I will try and leave the comments. thank you for your helps.
