### ISSUE TITLE
m0110_send err: 01

### ISSUE THREAD

**Issue by hsully03** [tmk/tmk_keyboard#695]
Hello, I'm currently building an m0110 to usb convertor, and I'm running into issues now that it's finished. I get no output from the keyboard, and HID_listen outputs this:

`sudo ./hid_listen.linux`

`Waiting for device:`

`Listening:`

`m0110_send err: 01`

`m0110_recv err: 01`

I can't find anything online about this error. What can I do to fix it? Thanks :)

**Comment by tmk** [comment]
I don't think it is a firmware bug, 
check If your converter and keyboard is electrically healthy.

You can ask further help or quesiton here.
https://geekhack.org/index.php?topic=24965.0
