### ISSUE TITLE
LUFA/ErgoDox: NKRO broken in recent builds

### ISSUE THREAD

**Issue by marknsikora** [tmk/tmk_keyboard#701]
I took over the cub-uanic/tmk_keyboard port of the ErgoDox classic a while back. Mostly just merging in the most recent changes. 

After pulling in 3c1700ee4eeb2b39f9692511525f9fb129e5763f the NKRO broke for my LUFA builds. 

Typing in qwerty instead yields 

```
gi fhi h egi efgi ghi
```

Don't have time to do a deep investigation right now. Mostly opening this in case other keybs are seeing similar issues.

**Comment by tmk** [comment]
Let us updated when you find something.

If you use Windows you want to remove device in device manager to remove driver configuration cache.


The change works as expected on my site, I just tested it with ibmpc_usb converter on Linux.
Difference in build options may cause the problem, you can check this Makefile for my configuration.
https://github.com/tmk/tmk_keyboard/blob/master/converter/ibmpc_usb/Makefile
