### ISSUE TITLE
NeXT non-ADB keyboard timing

### ISSUE THREAD

**Issue by spenczar** [tmk/tmk_keyboard#704]
I recently acquired a NeXT non-ADB keyboard, and have been exploring it pretty thoroughly with an oscilloscope and logic analyzer. Like you (https://github.com/tmk/tmk_keyboard/blob/master/tmk_core/protocol/next_kbd.c#L153-L162), I noticed that the timing of the keyboard's signal is not _quite_ 50 microseconds, or even 51 microseconds.

It turns out that the timing is actually 52.75 microseconds per pulse, corresponding to a frequency of 18,957 hertz. That's because the keyboard uses a Ceralock CSB455 oscillator:

![image](https://user-images.githubusercontent.com/880413/132966106-171b7f52-2053-4112-aa22-0970bb9248f1.png)

This oscillator has a frequency of 455 kHz, and drives the keyboard's signal, updating the pulse every 24 clock cycles. 455 kHz / 24 is 18.957 kHz - resulting in the 52.75 microsecond pulses.

I have no reason to believe your code is behaving _too_ badly, but at the least you might want to fix comments and the header settings, for example here:
https://github.com/tmk/tmk_keyboard/blob/a93677cbf145baf210f92a9129ded55c9ef5657b/tmk_core/protocol/next_kbd.h#L54

and here: https://github.com/tmk/tmk_keyboard/blob/8c0e245f52182055de1d10397b58373f2bdad46d/tmk_core/protocol/next_kbd.c#L62-L67

**Comment by tmk** [comment]
Thanks for the headsup.
I'll look into the timing when I setup NeXT keyboard and converter next time.

**Comment by spenczar** [comment]
FWIW, I wrote more about this here, including logic analyzer and oscilloscope images of the timing: https://journal.spencerwnelson.com/entries/nextkb.html

**Comment by tmk** [comment]
Thank you for your detailed writeup.

I also confirmed the bit width(52.75us) with my NeXT Keyboard using Logic Analyzer.

The converter can read signal at way better timing now.

Before Fix(signal read timing  at 9b99f8f)
![8GB83tI](https://user-images.githubusercontent.com/424590/163694842-45dfa4cd-df48-4849-a9f1-adbb4b0b336d.png)

After Fix(signal read timing at dcebfb4f)
![pL7NeW3](https://user-images.githubusercontent.com/424590/163694851-c49eeb2a-057e-4def-9642-0e5b820ff898.png)

In this capture the converter reads 'IN' at either edge of 'Read'.

**Comment by tmk** [comment]
Reimplemented NeXT converter interpreting the protocol as UART 9-bit data, not a long bit sequence. 

https://github.com/tmk/tmk_keyboard/wiki/NeXT#next-keyboard-protocol

https://github.com/tmk/tmk_keyboard/tree/master/converter/next_usb_ng
