### ISSUE TITLE
Modern keyboard -> PC 9821

### ISSUE THREAD

**Issue by toncho11** [tmk/tmk_keyboard#719]
Hi,

Is it possible to build a keybaord converter that enables a modern usb or ps2 keyboard to work on Japanese PC 9821 ?

**Comment by tmk** [comment]
Yes, you will able to use code of this project to handle input from USB or PS/2 keyboard. Then, you write code to output signal for "Japanese PC 9821".

**Comment by tmk** [comment]
No, I don't.
I don't know difference between 9821 and 9801, but you can find some resources about 9801 on the net, many are written in Japanese unfortunately.

This is my memo.
https://github.com/tmk/tmk_keyboard/wiki/PC-9801-Keyboard
