### ISSUE TITLE
The second button on the Macally ADB Mouse

### ISSUE THREAD

**Issue by Dandumontp** [tmk/tmk_keyboard#722]
Hi

I have a Macally ADB "two button" mouse and the second button will not work. I have searched a little, and the mouse use a proprietary protocol, but there is information about that on the GNU/Linux ADB driver (adbhid.c : https://elixir.bootlin.com/linux/latest/source/drivers/macintosh/adbhid.c)

Is there a way to add support for this mouse ? I have an adapter and i can try. 

Pierre

**Comment by tmk** [comment]
Add support for the mouse at cf26ad4ae.

For other mouses:
https://github.com/tmk/tmk_keyboard/issues/725
