### ISSUE TITLE
" LUFA may be too old or not found: try 'git submodule update --init'。"

### ISSUE THREAD

**Issue by SilenceGoo** [tmk/tmk_keyboard#742]
I downloaded the newest codes to try to compile on my Ubuntu environment, and this happened. Seems I missed some submodules or I missed smth somewhere? 

I always used a earlier tmk version codes in the past until today, so what I could do to avoid this in the updated project? Need specific steps, thanks.

**Comment by tmk** [comment]
You need to `git clone` this repo and then `git submodule update --init` will work.

**Comment by SilenceGoo** [comment]
Cool, I should use git more frequently from now on, everything seems working well now.

**thanks.**
