### ISSUE TITLE
PS/2 mouse support doesn't work

### ISSUE THREAD

**Issue by tmk** [tmk/tmk_keyboard#76]
At some point it looks like PS/2 mouse support was borken. I haven't used and updated this for long time.

At this time I can find serveral problems with PS/2 mouse.
## 1. ps2_mouse.c doesn't work[FIXED]
- doesn't work completely
- depends on PJRC stack API
## 2. PS2_MOUSE_ENABLE doesn't work[FIXED]
- common.mk has a problem
## 3. It doen't work with PS/2 converter
- keyboard and mouse doen't work at same time
- pin configuration cannot define both keyboard and mouse at same time
- two instances of ps2.c doesn't work at same time
## 4. PS/2 configuration[FIXED]
- select of ps/2 implemetations: BUSYWAIT, INTERRUPT or UART
- select of ps/2 code file: ps2.c or ps2_uart.c
## 5. refactoring is needed
- split ps2.c into busywait and intrrupt version.[FIXED]
- common functions and macros are located in one header file
- ring buffer utility. all in one header file?
- make two instances from one file to host keyboard and mouse at once at the same time.

**Comment by robszy** [comment]
In my ps2usb i've configured mouse to stream mode because i have no chance to send request byte for packet to mouse in the presence of vusb ints:
https://github.com/robszy/ps2usb/blob/master/ps2usb/src/mouse.c#L35

**Comment by tmk** [comment]
PS/2 mouse should be supported by ibmpc converter now.
